version: "3.9"

services:
  app:
    build: ./app
    environment:
      - POSTGRES_PASSWORD=powercloud
      - POSTGRES_USER=powercloud
      - POSTGRES_DB=powercloud_db
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      - db
  db:
    build: ./db
    environment:
      - POSTGRES_PASSWORD=powercloud
      - POSTGRES_USER=powercloud
      - POSTGRES_DB=powercloud_db
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    ports:
      - "5432:5432"
  api:
    build: ./api
    environment:
      - POSTGRES_PASSWORD=powercloud
      - POSTGRES_USER=powercloud
      - POSTGRES_DB=powercloud_db
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    ports:
      - "5000:5000"
#  gdal:
#    build: ./gdal
#    depends_on:
#      - db
